{% set name = "mantichora" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 69a9653dab788b20f79f48e2e0038525ee6ef342600b8b5750e45a8b35f9416e

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - atpbar >=1.0.2

test:
  imports:
    - mantichora

about:
  home: https://github.com/alphatwirl/mantichora
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A simple interface to multiprocessing'
  description: |
    Mantichora provides a simple interface to multiprocessing. You can
    simply give Mantichora as many functions as you need to run.
    Mantichora will run them concurrently in background processes by
    using multiprocessing and give you the return values of the
    functions. The return values are sorted in the order of the
    functions you have originally given to Mantichora. Progress bars
    from atpbar can be used in the functions.
  dev_url: https://github.com/alphatwirl/mantichora
  doc_url: https://github.com/alphatwirl/mantichora#mantichora

extra:
  recipe-maintainers:
    - TaiSakuma
