travis:
  secure:
    BINSTAR_TOKEN: J/j/hUAjFDiAHXxoIhRtqlX5fHAA99u9aNbc+CTo0GxCLOcVbGxa/185UjqKP7wrCwpQyUAFnKh6Kg6fkcmwSnSpWV9OK+VyZgX9Cb4GNPidRbzfQ08ACeN1snqh53GoilMpbq9kZN7j3OjvSf7db22fxfrMy8cXNrAD32ANlTQQn4yzYt34962T45NpFSxul2yyA5pzcsnJpkxxEIe4FJ5dPgUeNWdcVlbJPixhrwgA7ZzHbzn2QJHI4tBdgip3ld20QL1+6y2tFFd7aJkjGa+z0x0OS/ALfV8veijlJoetL0dEsMtJMOiWBacS/q8VIfxKcs9L7mxwiznfWYAZ+L50asLguvPDDOfydrkEoCE6ll2fGOsORsJZ+8ERuLcKxaeCkABHl3tOcIcIjnnAEYjNxJsKbmoWE6mXCqse5djxtk39EwxK9juWUizg8anQWyfYFpyfq21XWBIie9TwHKECF4NrEb+LLlOyKoyKdl8LBbHl+ZyM8sZRRKV55rfay4OFDlAurl+5LQrIyxKlSNKHEto8GPt3W2AD3bThrzP6eXCGKY6xFh5ms+JAiWAHcAGgjJ5BV79X2wzbTWfX9dCgLbV3Bjakq+kLiBZlrbPQxQdOjhV0GCUK5sSD9Y1Bo+RXHIMF2vzwhZdplnPagRCvlYSgUghR8QUwXBeSros=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
